spring:
  application:
    name: lyraWiki
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wiki
    username: root
    password: 365373011
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    generator:
      write_numbers_as_strings: true
springdoc:
  packages-to-scan: com.lyra.wiki.controller
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl