spring:
  application:
    name: lyra-wiki
  datasource:
    url: jdbc:mysql://121.4.39.168:3306/wiki
    username: root
    password: 365373011
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    generator:
      write_numbers_as_strings: true
  redis:
    host: 121.4.39.168
    port: 6379
    password: 365373011
  servlet:
    multipart:
      max-file-size: 10MB
  thymeleaf:
    cache: false
springdoc:
  packages-to-scan: com.lyra.wiki.controller
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
